include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
  BUNDLE: 'org.gnome.Screenshot.Devel.flatpak'

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Screenshot.json'
    MESON_ARGS: ''
    FLATPAK_MODULE: 'gnome-screenshot'
    RUNTIME_REPO: 'https://sdk.gnome.org/gnome-nightly.flatpakrepo'
    APP_ID: 'org.gnome.Screenshot'

review:
  dependencies:
    - 'flatpak'
  extends: '.review'

stop_review:
  extends: '.stop_review'
