.TH "GNOME-SCREENSHOT" "1" "August 10, 2013" "" ""
.SH NAME
gnome-screenshot \- capture the screen, a window, or an user-defined area and save the snapshot image to a file.
.SH SYNOPSIS
.sp
\fBgnome-screenshot\fR [ \fB-c\fR ]  [ \fB-w\fR ]  [ \fB-a\fR ]  [ \fB-b\fR ]  [ \fB-B\fR ]  [ \fB-p\fR ]  [ \fB-d \fISECONDS\fB \fR ]  [ \fB-e \fIEFFECT\fB \fR ]  [ \fB-i\fR ]  [ \fB-f \fIFILENAME\fB \fR ]  [ \fB--display \fIDISPLAY\fB \fR ]
.SH "DESCRIPTION"
.PP
\fBgnome-screenshot\fR is a GNOME utility for taking
screenshots of the entire screen, a window or a user-defined area of the screen.
.SH "OPTIONS"
.TP
\fB-c, --clipboard\fR
Send the grab directly to the clipboard.
.TP
\fB-w, --window\fR
Grab the current active window instead of the entire
screen.
.TP
\fB-a, --area\fR
Grab an area of the screen instead of the entire screen.
.TP
\fB-b, --include-border\fR
Include the window border within the screenshot. Note: This option is deprecated
and window border is always included.
.TP
\fB-B, --remove-border\fR
Remove the window border from the screenshot. Note: This option is deprecated
and window border is always included.
.TP
\fB-p, --include-pointer\fR
Include the pointer with the screenshot.
.TP
\fB-d, --delay=\fISECONDS\fB,\fR
Take the screenshot after the specified delay [in seconds].
.TP
\fB-e, --border-effect=\fIEFFECT\fB,\fR
Add an effect to the outside of the screenshot border.
\fIEFFECT\fR can be ``shadow''
(adding drop shadow), ``border'' (adding rectangular
space around the screenshot), ``vintage'' (desaturating
the screenshot slightly, tinting it and adding
rectangular space around it) or ``none'' (no effect).
Default is ``none''. Note: This option is deprecated
and is assumed to be ``none''.
.TP
\fB-i, --interactive\fR
Interactively set options in a dialog.
.TP
\fB-f, --file=\fIFILENAME\fB\fR
Save screenshot directly to this file.
.TP
\fB--display=\fIDISPLAY\fB\fR
X display to use.
.TP
\fB-?, -h, --help\fR
Show a summary of the available options.
.PP
In addition, the usual GTK+ command line options apply.
See the output of --help for details.
.SH "AUTHOR"
.PP
This manual page was written by Christian Marillat <marillat@debian.org> for
the Debian GNU/Linux system (but may be used by others).
.PP
Updated by Theppitak Karoonboonyanan
<thep@linux.thai.net>, Tom Feiner <feiner.tom@gmail.com>, Cosimo Cecchi <cosimoc@gnome.org> and others.
